---
- name: Determine application name
  set_fact:
    appimage_application_name: >-
      {% if install_complex_url.name is defined -%}
      {{ (install_complex_url.name|trim) }}
      {% else -%}
      {{ (install_complex_url.url|basename).split('-')[0]|lower|trim }}
      {% endif -%}

- name: INSTALL APPLICATION
  when: (install_complex_url.state is not defined or
        (install_complex_url.state is defined and install_complex_url.state|lower != 'absent')
        )
  block:
    - name: CHECK IF "{{ install_complex_url.url|basename }}" IS ALREADY IN PLACE
      stat:
        path: "{{ appimage_installation_dir }}/{{ install_complex_url.url|basename }}"
      register: _appimage_install_status

    - name: DOWNLOAD MISSING APPIMAGES FOR "{{ appimage_application_name }}"
      become: true
      get_url:
        url: "{{ install_complex_url.url }}"
        mode: '0555'
        dest: "{{ appimage_installation_dir }}/{{ install_complex_url.url|basename }}"
      when: not _appimage_install_status.stat.exists

    - name: CREATE APPALIASES SIMPLE
      become: true
      file:
        state: link
        src: "{{ appimage_installation_dir }}/{{ install_complex_url.url|basename }}"
        dest: "{{ appimage_binary_dir }}/{{ appimage_application_name|trim }}"
        owner: root
        group: root

- name: REMOVE APPLICATION
  become: true
  when:
    - install_complex_url.state is defined
    - install_complex_url.state|lower == 'absent'
  block:
    - name: REMOVE ALIAS "{{ appimage_binary_dir }}/{{ appimage_application_name|trim }}"
      become: true
      file:
        state: absent
        path: "{{ appimage_binary_dir }}/{{ appimage_application_name|trim }}"

    - name: REMOVE APPIMAGE FILE "{{ install_complex_url.url|basename }}"
      become: true
      file:
        state: absent
        path: "{{ appimage_installation_dir }}/{{ install_complex_url.url|basename }}"
