---
# Simple installation routine
- name: Install simple | Check if the app is already in place.
  ansible.builtin.stat:
    path: "{{ appimage_installation_dir }}/{{ install_simple_url | basename }}"
  register: _appimage_install_status

- name: Install simple | Download missing appimages.
  become: true
  ansible.builtin.get_url:
    url: "{{ install_simple_url }}"
    mode: '0555'
    dest: "{{ appimage_installation_dir }}/{{ install_simple_url | basename }}"
  when: not _appimage_install_status.stat.exists

- name: Install simple | Create appalias
  become: true
  ansible.builtin.file:
    state: link
    src: "{{ appimage_installation_dir }}/{{ install_simple_url | basename }}"
    dest: "{{ appimage_binary_dir }}/{{ (install_simple_url | basename).split('-')[0] | lower }}"
    owner: root
    group: root
