---
- name: Install | Manage appimage directory "{{ appimage_installation_dir }}"
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ appimage_installation_dir }}"
    owner: "{{ appimage_owner }}"
    group: "{{ appimage_group }}"
    mode: '0755'

- name: Install | Manage app installatio simple.
  ansible.builtin.include_tasks: install_simple.yml
  vars:
    install_simple_url: "{{ item }}"
  when:
    - item is string
    - item is not mapping
  loop: "{{ appimage_download_urls }}"

- name: Install | Manage app installation complex.
  ansible.builtin.include_tasks: install_complex.yml
  vars:
    install_complex_url: "{{ item }}"
  when: item is mapping
  loop: "{{ appimage_download_urls }}"
