---
- name: Converge
  hosts: all
  tasks:
    - name:  MOLECULE - INCLUDE VARIABLES
      ansible.builtin.include_vars: ./variables.yml

    - name: "Include spreadcat.appimage"
      ansible.builtin.include_role:
        name: "spreadcat.appimage"
