---
- name: Converge containers.
  hosts: all
  tasks:
    - name: Converge | Inlcude variables.
      ansible.builtin.include_vars: ./variables.yml

    - name: Converge | Include spreadcat.appimage role.
      ansible.builtin.include_role:
        name: "spreadcat.appimage"
